name: AoC 2022

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run eslint
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '19.x'
      - run: yarn
      - run: yarn eslint .
  jest:
    runs-on: ubuntu-latest
    name: Run tests
    needs: [lint]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '19.x'
      - run: yarn
      - run: yarn test
